#!/usr/bin/env python3
"""Freeze 3: code personal Gmail remainder and keeganmoody33 calendar.

Does not recode Freeze 1 Gmail or Freeze 2 platform files.
Opportunities stay out of the application census.
"""

from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent
CODER = "freeze3"

APP_FIELDS = [
    "coder_id",
    "application_id",
    "cycle",
    "company_canonical",
    "company_as_listed",
    "underlying_employer",
    "role_as_listed",
    "role_lane",
    "gtm_modifier",
    "date_applied",
    "date_precision",
    "date_capture",
    "date_evidence_anchor",
    "discovery_source",
    "submission_channel",
    "ats_system",
    "evidence_tier",
    "evidence_class",
    "register",
    "terminal_outcome",
    "terminal_outcome_date",
    "terminal_outcome_precision",
    "location",
    "work_type",
    "level_as_listed",
    "salary_range_listed",
    "confidence",
    "notes",
]

EVENT_FIELDS = [
    "coder_id",
    "event_id",
    "application_id",
    "event_date",
    "event_date_precision",
    "event_type",
    "round_number",
    "counterparty_name",
    "counterparty_role",
    "medium",
    "evidence_system",
    "evidence_id",
    "notes",
]

EXCL_FIELDS = [
    "coder_id",
    "candidate_id",
    "date",
    "company",
    "role",
    "exclusion_reason",
    "what_would_promote_it",
    "evidence_system",
    "evidence_id",
]


def write_csv(path: Path, fields: list[str], rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fields})


def main() -> None:
    apps = [
        {
            "application_id": "pin|unspecified|c1",
            "cycle": "1",
            "company_canonical": "Pin",
            "company_as_listed": "Pin",
            "underlying_employer": "",
            "role_as_listed": "unspecified",
            "role_lane": "unspecified",
            "gtm_modifier": "",
            "date_applied": "2025-06-26",
            "date_precision": "evidence_bound",
            "date_capture": "",
            "date_evidence_anchor": "2025-06-26",
            "discovery_source": "recruiter_inbound",
            "submission_channel": "unknown",
            "ats_system": "none_observed",
            "evidence_tier": "B",
            "evidence_class": "employer_artifact",
            "register": "opportunity",
            "terminal_outcome": "rejected_after_interview",
            "terminal_outcome_date": "2025-07-07",
            "terminal_outcome_precision": "exact",
            "location": "unstated",
            "work_type": "unstated",
            "level_as_listed": "",
            "salary_range_listed": "not_stated",
            "confidence": "high",
            "notes": "No ATS receipt. Erica Stacy Tarwater at pin.com booked a 1 hour meeting. Conor Kline 30 min followed. Assignment requested then process closed. Role omitted.",
        },
        {
            "application_id": "hotglue|bdm|c1",
            "cycle": "1",
            "company_canonical": "Hotglue",
            "company_as_listed": "hotglue",
            "underlying_employer": "",
            "role_as_listed": "BDM Role",
            "role_lane": "sales_bd_partnerships",
            "gtm_modifier": "",
            "date_applied": "2026-04-15",
            "date_precision": "evidence_bound",
            "date_capture": "",
            "date_evidence_anchor": "2026-04-15",
            "discovery_source": "recruiter_inbound",
            "submission_channel": "unknown",
            "ats_system": "none_observed",
            "evidence_tier": "B",
            "evidence_class": "employer_artifact",
            "register": "opportunity",
            "terminal_outcome": "still_open",
            "terminal_outcome_date": "",
            "terminal_outcome_precision": "",
            "location": "unstated",
            "work_type": "unstated",
            "level_as_listed": "",
            "salary_range_listed": "not_stated",
            "confidence": "high",
            "notes": "Kevin Wright at hotglue.io reached out on LinkedIn. Calendar title Keegan + Kevin: Hotglue BDM Role. No ATS receipt. No decline in the freeze.",
        },
        {
            "application_id": "opsin|unspecified|c1",
            "cycle": "1",
            "company_canonical": "Opsin",
            "company_as_listed": "Opsin Security",
            "underlying_employer": "",
            "role_as_listed": "unspecified",
            "role_lane": "unspecified",
            "gtm_modifier": "",
            "date_applied": "2026-03-12",
            "date_precision": "evidence_bound",
            "date_capture": "",
            "date_evidence_anchor": "2026-03-12",
            "discovery_source": "recruiter_inbound",
            "submission_channel": "unknown",
            "ats_system": "none_observed",
            "evidence_tier": "B",
            "evidence_class": "employer_artifact",
            "register": "opportunity",
            "terminal_outcome": "still_open",
            "terminal_outcome_date": "",
            "terminal_outcome_precision": "",
            "location": "unstated",
            "work_type": "unstated",
            "level_as_listed": "",
            "salary_range_listed": "not_stated",
            "confidence": "medium",
            "notes": "Adrianna Iadarola at colossustg.com sent Video Interview with James Pham and called it a 2nd round with a take-home after. No ATS receipt. Role omitted. Intermediary Colossus TG. Client Opsin Security.",
        },
    ]
    for row in apps:
        row["coder_id"] = CODER

    events = [
        {
            "event_id": "pin|unspecified|c1|e1",
            "application_id": "pin|unspecified|c1",
            "event_date": "2025-06-26",
            "event_date_precision": "exact",
            "event_type": "employer_ack",
            "round_number": "",
            "counterparty_name": "Erica Stacy Tarwater",
            "counterparty_role": "hiring",
            "medium": "email",
            "evidence_system": "gmail",
            "evidence_id": "gth_fe49801b0505bbbc",
            "notes": "Cal.com booking for 1 Hour Meeting.",
        },
        {
            "event_id": "pin|unspecified|c1|e2",
            "application_id": "pin|unspecified|c1",
            "event_date": "2025-06-30",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "Erica Stacy Tarwater",
            "counterparty_role": "hiring",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_ad843b81c501a0fe",
            "notes": "1 Hour Meeting. User recalled Erika. Calendar and mail use Erica.",
        },
        {
            "event_id": "pin|unspecified|c1|e3",
            "application_id": "pin|unspecified|c1",
            "event_date": "2025-07-07",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "2",
            "counterparty_name": "Conor Kline",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_1d949b06d7b86c9a",
            "notes": "30 Min Meeting. Assignment was due before this meeting.",
        },
        {
            "event_id": "pin|unspecified|c1|e4",
            "application_id": "pin|unspecified|c1",
            "event_date": "2025-07-07",
            "event_date_precision": "exact",
            "event_type": "rejection",
            "round_number": "",
            "counterparty_name": "Erica Stacy Tarwater",
            "counterparty_role": "hiring",
            "medium": "email",
            "evidence_system": "gmail",
            "evidence_id": "gth_fe49801b0505bbbc",
            "notes": "Not moving forward after listening to the Conor interview.",
        },
        {
            "event_id": "hotglue|bdm|c1|e1",
            "application_id": "hotglue|bdm|c1",
            "event_date": "2026-04-15",
            "event_date_precision": "exact",
            "event_type": "employer_ack",
            "round_number": "",
            "counterparty_name": "Kevin Wright",
            "counterparty_role": "unknown",
            "medium": "email",
            "evidence_system": "gmail",
            "evidence_id": "gth_e5448b420f510900",
            "notes": "LinkedIn outreach then calendar invite for BDM Role.",
        },
        {
            "event_id": "hotglue|bdm|c1|e2",
            "application_id": "hotglue|bdm|c1",
            "event_date": "2026-04-20",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "Kevin Wright",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_ccc88f3db9f64129",
            "notes": "Keegan + Kevin: Hotglue BDM Role.",
        },
        {
            "event_id": "opsin|unspecified|c1|e1",
            "application_id": "opsin|unspecified|c1",
            "event_date": "2026-03-12",
            "event_date_precision": "exact",
            "event_type": "employer_ack",
            "round_number": "",
            "counterparty_name": "Adrianna Iadarola",
            "counterparty_role": "recruiter",
            "medium": "email",
            "evidence_system": "gmail",
            "evidence_id": "gth_e756940c516829cf",
            "notes": "Video Interview prep. Recruiter said 2nd round is a take-home.",
        },
        {
            "event_id": "opsin|unspecified|c1|e2",
            "application_id": "opsin|unspecified|c1",
            "event_date": "2026-03-13",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "James Pham",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_d8dafd5d42786dbb",
            "notes": "Opsin Sync. Recruiter labeled it a video interview. Round number uncertain because recruiter also called a later take-home the 2nd round.",
        },
        {
            "event_id": "beautiful-ai|unspecified|c1|e4",
            "application_id": "beautiful-ai|unspecified|c1",
            "event_date": "2026-03-17",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "Brandon Ness",
            "counterparty_role": "hiring manager",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_68d3d2165c13499a",
            "notes": "Personal calendar title Interview with beautiful.ai. Corroborates Freeze 1 gmail follow-up. Does not add a new interviewed application.",
        },
        {
            "event_id": "every-to|gtm-engineer|c1|e3",
            "application_id": "every-to|gtm-engineer|c1",
            "event_date": "2026-04-21",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "Austin",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_eb10d6eb86410a16",
            "notes": "30 min with Austin. Q6 sent mail booked 12:15 the day before.",
        },
        {
            "event_id": "phrasiq|unspecified|c1|e5",
            "application_id": "phrasiq|unspecified|c1",
            "event_date": "2026-04-15",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "2",
            "counterparty_name": "unknown",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_4906d7d8bd299c13",
            "notes": "GTM Deep Dive occurred on the personal calendar. Freeze 1 only had a proposed date.",
        },
        {
            "event_id": "the-hog|gtm-engineer|c1|e5",
            "application_id": "the-hog|gtm-engineer|c1",
            "event_date": "2026-06-16",
            "event_date_precision": "exact",
            "event_type": "hiring_manager_interview",
            "round_number": "1",
            "counterparty_name": "Hudson Liao",
            "counterparty_role": "unknown",
            "medium": "video",
            "evidence_system": "gcal",
            "evidence_id": "cal_629a071abb61bce9",
            "notes": "Personal calendar. Freeze 1 already had the invitation. The Hog remains opportunity.",
        },
    ]
    for row in events:
        row["coder_id"] = CODER

    exclusions = [
        {
            "candidate_id": "bcofa-gtm-consulting",
            "date": "2026-03-06",
            "company": "BCOFA",
            "role": "unspecified",
            "exclusion_reason": "consulting_prospect",
            "what_would_promote_it": "An employment application receipt for a named role, not a client GTM project.",
            "evidence_system": "gcal",
            "evidence_id": "cal_4b2dcb68665185f7",
        },
        {
            "candidate_id": "truebuilt-gtm-project",
            "date": "2026-07-15",
            "company": "TrueBuilt",
            "role": "GTM project",
            "exclusion_reason": "consulting_prospect",
            "what_would_promote_it": "Nothing. The LinkedIn Easy Apply GTM Engineer row is already in Freeze 2. This thread is a separate project quote that they passed on budget.",
            "evidence_system": "gmail",
            "evidence_id": "gth_02dcef5402e849cd",
        },
        {
            "candidate_id": "mobb-employment",
            "date": "2025-06-03",
            "company": "Mobb.dev",
            "role": "Business Development",
            "exclusion_reason": "unknown",
            "what_would_promote_it": "Nothing. Gusto first-day mail and a Mobb employment mailbox are employment onboarding, not a search application.",
            "evidence_system": "gmail",
            "evidence_id": "gth_96b8c659b5fa2546",
        },
        {
            "candidate_id": "mixmax-heath-meeting",
            "date": "2025-08-14",
            "company": "Mixmax",
            "role": "unspecified",
            "exclusion_reason": "marketplace_profile",
            "what_would_promote_it": "An employment application receipt. Product or contractor meetings do not promote it.",
            "evidence_system": "gcal",
            "evidence_id": "cal_3e5387362a5b33e3",
        },
        {
            "candidate_id": "kivira-weekly-outbound",
            "date": "2026-06-03",
            "company": "Kivira.health",
            "role": "unspecified",
            "exclusion_reason": "consulting_prospect",
            "what_would_promote_it": "An employment application receipt. Weekly outbound check-ins are client work.",
            "evidence_system": "gcal",
            "evidence_id": "cal_cc9f94b847eb65aa",
        },
    ]
    for row in exclusions:
        row["coder_id"] = CODER

    write_csv(OUT / "applications__freeze3.csv", APP_FIELDS, apps)
    write_csv(OUT / "events__freeze3.csv", EVENT_FIELDS, events)
    write_csv(OUT / "exclusions__freeze3.csv", EXCL_FIELDS, exclusions)
    print("wrote freeze3 applications", len(apps), "events", len(events), "exclusions", len(exclusions))


if __name__ == "__main__":
    main()
